tracker:
  _target_: src.modules.baselines.combined_oracle.CombinedOracle
  iou_threshold: 0.10
  model:
    _target_: src.modules.samara_hiera_model.SamaraHieraModel
    sam_model_path: tm/sam_large.pt
    crop_resize: 512
    pad_ratio: 1.0

  main_memory:
    _target_: src.modules.memories.main_memory.MainMemory
    max_memory_history: 6
    max_pointer_history: 15

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: combined_oracle
  video_path: data/visualize
