tracker:
  _target_: src.modules.samara_controller.SamaraController
  commit_threshold: 0.5   
  select: True    
  gate: True      
  model:
    _target_: src.modules.samara_hiera_model.SamaraHieraModel
    sam_model_path: tm/sam_large.pt
    crop_resize: 448
    pad_ratio: 0.25
    feature_encoder: perception
  main_memory:
    _target_: src.modules.memories.main_memory.MainMemory
    max_memory_history: 6
    max_pointer_history: 6

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: samara_controller
  video_path: data/visualize/samara_controller
