tracker:
  _target_: src.modules.baselines.memory_oracle.MemoryOracle
  iou_threshold: 0.40
  model:
    _target_: src.modules.models.samara_hiera_model.SamaraHieraModel
    sam_model_path: tm/sam_large.pt
    padding_size: 12
    crop_resize: 384
    n_references: 9
    
  main_memory: 
    _target_: src.modules.memories.main_memory.MainMemory
    max_memory_history: 6
    max_pointer_history: 15

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: sam baseline
  video_path: data/visualize