defaults:
  - trackers@tracker: baselines/memory_oracle

detection_data:
  _target_: src.typing.detection_data.DetectionData
  amodal_directory: data/person_path/amodal
  visible_directory: data/person_path/visible
  video_directory: data/person_path/videos
  load_frames: True
  num_threads: 32

person_path:
  _target_: src.typing.person_path.PersonPath
  main_directory: data/person_path
  occlusion_ranges: [2, 150]
  n_experiments: 1200
  n_after_occlusion: 50
  random_seed: 44
  min_visible_ratio: 0.7
  resize_resolution: 1024
  min_visible_area: 500
  max_visible_area: null
  max_distractor_overlap: 0.30
  min_distractor_overlap: 0.00
  non_targets:
    - "crowd"
    - "person_in_vehicle"
    - "reflection"
    - "person_in_background"
    - "severly_occluded_person"

dataset_path: data/memory_oracle
shard_index: 0
num_shards: 1

crop_resize: 512
pad_ratio: 0.25
random_seed: 42
