defaults:
  - trackers@tracker: baselines/mask_oracle

detection_data:
  _target_: src.typing.detection_data.DetectionData
  amodal_directory: data/person_path/amodal
  visible_directory: data/person_path/visible
  video_directory: data/person_path/videos
  load_frames: True
  num_threads: 32

person_path:
  _target_: src.typing.person_path.PersonPath
  main_directory: data/person_path
  n_experiments: 1200
  random_seed: 44
  first_occ_min: 7
  border_inset: 8  
  n_after_occlusion: 30
  min_visible_area: 900
  min_visible_ratio: 0.90
  occlusion_ranges: [2, 50] 
  max_distractor_overlap: 0.6
  non_targets: [crowd, person_in_vehicle, reflection, person_in_background, severly_occluded_person, sitting_person, person_on_open_vehicle]


dataset_path: data/mask_oracle
shard_index: 0
num_shards: 1

corruption_probabilities: [0.0, 0.05, 0.1, 0.15, 0.2]

max_frames: 300
crop_resize: 448
pad_ratio: 0.25
random_seed: 42
