defaults:
  - offline_trainers: cnn_fixed_samara
  - trackers@tracker: memory_oracle
  
detection_data:
  _target_: src.typing.detection_data.DetectionData
  amodal_directory: data/person_path/amodal
  visible_directory: data/person_path/visible
  video_directory: data/person_path/videos
  load_frames: True
  num_threads: 32
  resize_resolution: 1024

train_test_split: 0.3
deploy_controller: True
dataset_path: data/memory_oracle/memory/padding_0.10
commit_threshold: 0.4