tracker:
  _target_: src.modules.baselines.samurai.Samurai
  checkpoint: tm/sam_large.pt
  model_config: SAM2/samurai_hiera_large.yaml

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: samurai_large
  video_path: data/visualize/samurai_large
