tracker:
  _target_: src.modules.baselines.sam_baseline.SAMBaseline
  iou_threshold: 0.2

  model:
    _target_: src.modules.models.samara_hiera_model.SamaraHieraModel
    sam_model_path: tm/sam_large.pt
    padding_size: 12
    crop_resize: 384
    n_references: 10

  main_memory:
    _target_: src.modules.memories.main_memory.MainMemory
    max_memory_history: 6
    max_pointer_history: 15

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: sam_baseline_20
  video_path: data/visualize/sam_baseline_20
