tracker:
  _target_: src.modules.baselines.samite.Samite
  checkpoint: tm/sam_small.pt
  model_config: SAM2/samite_hiera_small.yaml

experiment:
  _target_: src.experiments.tracking_experiment.TrackingExperiment
  resolution: 1024
  experiment_name: samite_small
  video_path: data/visualize/samite_small
